name: New Issue

on: 
  issues:
    types:
      - opened

jobs: 
  comment-on-issue: 
    runs-on: ubuntu-latest
    steps:
      - name: Issue comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          number: 1
          comment: Comment for Issue or GitHub Pull Request
      
